name: Code linting

on:
  push:

jobs:
  Biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          
      - name: install
        run: npm ci

      - name: Run Biome
        run: npm run lint
