name: Code linting

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install
        run: npm ci
      - name: Run Biome
        run: npm run lint:apply
