name: Code linting

on:
  push:

jobs:
  Biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install
        run: npm ci
      - name: Run Biome
        run: npm run lint:apply
